### ISSUE TITLE
Remove "premium bypass" feature

### ISSUE THREAD

**Issue by insidewhy** [hyugogirubato/Kamyroll-Python#12]
1. Using an account in this way is against crunchyroll terms, crunchyroll can easily detect a single account being used by many different IPs and locations. At best they will then just terminate the account, at worst they can try to take the account owner (or whoever stole the account) to court.
2. If this wasn't enough to persuade you, the mechanism that Kamyroll uses to store the account details is so easy to crack. Anyone with the source code can easily determine the login and password of the account. They could then easily login to the account and change the password. That's a lot of trust to put in your users.
3. I'm really happy to contribute to this application, but not when it has this feature. I love that crunchyroll provide a way to legally watch anime, the ability to download videos for offline usage is great but I think offering an ability that allows people to steal from crunchyroll without paying is really uncool. If this feature remains I have no choice but to fork the application, remove the bypass functionality, and continue development of the app under a different name.

This is a really bad idea. The program is useful but the premium bypass is illegal and insensible. Please just remove it, you don't want to give crunchyroll anymore reasons to stop this app from working then they already have.

**Comment by proall** [comment]
I agree.

**Comment by hyugogirubato** [comment]
@insidewhy 
I got the message, I will remove the currently compiled version of kamyroll with this feature, I will republish in the next few days a patch that will permanently remove this feature for Kamyroll-Python.
