### ISSUE TITLE
pip install kamyroll_python 

### ISSUE THREAD

**Issue by hyugogirubato** [hyugogirubato/Kamyroll-Python#13]
Hey @insidewhy

As you will probably notice I just updated the code of the script and I did a small reorganization of the files on the GitHub. Following this update, I blocked the installation with pip due to incompatibility (maybe because I replaced all double quotes with single ones.). Knowing that I don’t know much about creating a pip library, you can make sure that the program is again compatible with pip.

I made sure not to change the code you added last time for compatibility with Linux, so I don’t see why it doesn’t work... And also when you change the code, try not to change the sentence tabulation because it is very ugly to read so not practical when I connect and especially very long to put back correctly.

PS: If you want to discuss in private, I am on the Discord server (in description of README).

Thank!

hyugogirubato

**Comment by insidewhy** [comment]
@hyugogirubato 

```python
# from . import extractor
# from . import utils
import extractor
import utils
```

It's because you made changes like this again. Did you try to run the script with `pipenv` as I showed before?

**Comment by insidewhy** [comment]
Also deleting everything and moving it into a python directory didn't really help.

It's kinda hard to work on this when you keep deleting and undoing everything I've done so I guess I'll just maintain my own fork with a different name.

**Comment by insidewhy** [comment]
BTW there's no need to change quotation marks and stuff like that, just use `pipenv run format` to reformat the code to standard python style. You can type the quotation marks however you want, if you just use this command it'll update the code for you.

**Comment by hyugogirubato** [comment]
@insidewhy 
Okay, too bad, but I understand, so I am going to redo the organization of the repo and remove all the PIP functions that are no longer operational. For the installation by PIP I will make a link to your repo.
