### ISSUE TITLE
Error "Unable to connect to the site with this ip address"

### ISSUE THREAD

**Issue by RaulRohjans** [hyugogirubato/Kamyroll-Python#2]
Hello, I am trying to login to crunchyroll and I get the error in the title. I am using ubuntu 20.04 in a vps located in Germany (I know that in the US people only have access to crunchyroll beta now). I am using a virtual environment with python 3.9 and I have requests installed.

![Screenshot_20210715-112248_JuiceSSH](https://user-images.githubusercontent.com/77687494/125773190-793d5d0a-d136-4d08-8df9-70f4a49732e8.jpg)

**Comment by hyugogirubato** [comment]
@RaulRohjans 
Mm, are you using a personal VPN or are you using bypass?

Ha, silly question lol, I only made the modification in the application.

So, to be honest, this is a problem related to your IP (internet connection), so I don’t have a modification solution to offer you. On the other hand, if you are using a personal VPN it may be the IP address that is blocked by Crunchyroll. The beta API is accessible from any location. So, to use a VPN (or a fake location) to unblock the catalog, you have the option to enable us-unblocker which is by default set to US, **BUT** if you want another location it is possible, just change the country code (or us) by a compatible code attached.

**Note:** it seems to me that the bypass-country in Germany is not compatible unfortunately, but you still have the option to choose another location.

**List of compatible location codes:**
ar - Argentina
at - Austria
au - Australia
be - Belgium
bg - Bulgaria
br - Brazil
ca - Canada
ch - Switzerland
cl - Chile
co - Colombia
cz - Czech Republic
de - Germany
dk - Denmark
es - Spain
fi - Finland
fr - France
gb - United Kingdom (Great Britain)
gr - Greece
hk - Hong Kong
hr - Croatia
hu - Hungary
id - Indonesia
ie - Ireland
il - Israel
in - India
is - Iceland
it - Italy
jp - Japan
kr - Korea, Republic of
mx - Mexico
nl - Netherlands
no - Norway
nz - New Zealand
pl - Poland
ro - Romania
ru - Russian Federation
se - Sweden
sg - Singapore
sk - Slovakia
tr - Turkey
uk - United Kingdom
us - United States of America

**Comment by RaulRohjans** [comment]
I tried using the unblocker, but it results in the following error:

![imagem](https://user-images.githubusercontent.com/77687494/125801643-d71e1722-05a1-4128-99ec-1ed2a61c056e.png)

**Comment by RaulRohjans** [comment]
I was able to login on another machine with a different ip successfully. The thing is, if I try to download something with a link, it gives an error:

![imagem](https://user-images.githubusercontent.com/77687494/125802614-11c1e052-d091-4190-851c-dd3522afcb4d.png)


If instead of a link I try to use an ID (I got this id from making a search), it says there are no streams for that id.


![imagem](https://user-images.githubusercontent.com/77687494/125802769-b1ee3858-a9ec-4a0d-a6c6-cbd1e98e92db.png)

**Comment by hyugogirubato** [comment]
@RaulRohjans 
I understood your mistake, so I may not have been specific enough on how to use the script.I will explain how to do it, but if you have questions, I would be more responsive on discord.

So the script is not used with the links or the website crunchyroll, everything is done thanks to the script.
You must first log in with your account to update the config file and API accesses.
Then you have to look for the series you want, the kamyroll.py --search "one piece".
Once you search you will have a list of series with ids, copy you paste the id of the serie you want.
Then you have to display the seasons by doing kamyroll.py --seasons "ID copy in the clipboard".
Same step for the seasons, you copy the id of the one you are interested in.
Then you display the episodes of the season with the command kamyroll.py --episodes"Season ID copy in the clipboard
So same principle, the list of ep is displayed with the associated id. Copy the desired episode id and display the formats with the kamyroll.py command --formats "Episode ID [...]"
Once the formats are displayed, you can download the videos (or sosu titles) by doing the command kamyroll.py --download "Episode ID" --format "FORMAT copy in the clipboard"

**Comment by RaulRohjans** [comment]
Thank you so much, everything is working like it should now! I feel really dumb, sorry for wasting your time.
