### ISSUE TITLE
Where is the APK version?

### ISSUE THREAD

**Issue by Leike-Dev** [hyugogirubato/Kamyroll-Python#9]
I can't find the apk version of Kamyroll anymore. Would you know what happened? 😕

**Comment by insidewhy** [comment]
@Leike-Dev I'm not sure if there was an apk version, but now you can install kamyroll via `pip` using `pip install kamyroll_python`

**Comment by hyugogirubato** [comment]
@Leike-Dev 
The APK version is available on the github server indicate on the README pages, go for a ride.
For information, we had to put the kamyroll (APK) project in private following a Funimation rush on github.
